language: generic
dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
    - libglu1-mesa-dev

env:
  global:
    - INSTALL_EDM_VERSION=3.0.1
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - env: RUNTIME=3.6 TOOLKITS="pyqt5"
    - os: osx
      env: RUNTIME=3.6 TOOLKITS="pyqt5"
  fast_finish: true

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  # libdbus and libxkb for Pyside2, libsdl for wxpython
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libsdl1.2debian; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install -y wheel click coverage
install:
  - for toolkit in ${TOOLKITS}; do edm run -- python etstool.py install --runtime=${RUNTIME} --toolkit=${toolkit} || exit; done
  - if [[ ${TRAVIS_EVENT_TYPE} == 'cron' ]]; then for toolkit in ${TOOLKITS}; do edm run -- python etstool.py install --runtime=${RUNTIME} --toolkit=${toolkit} --source || exit; done; fi
script:
  - for toolkit in ${TOOLKITS}; do edm run -- python etstool.py test --runtime=${RUNTIME} --toolkit=${toolkit} || exit; done
after_success:
  - edm run -- python etstool.py flake8
  - ls
  # Add upload of coverage file to coverage service
  - bash <(curl -s https://codecov.io/bash) -Z -c -f test_coverage.xml
