@startuml

'class DataElement
'DataElement <|-- DataFramePlotManager
'DataElement <|-- DataFrameAnalyzer
class DataFrameAnalyzer {
    DataFrame source_df
    DataFrame filtered_df
    DataFrame displayed_df
    DataFrame summary_df
    DataFrame summary_categorical_df
    [DataFramePlotManager] plot_manager_list
}
DataFrameAnalyzer o--> DataFrame
DataFrameAnalyzer "0..*" o--> DataFramePlotManager

class DataFramePlotManager {
    DataFrame data_source
    [PlotDescriptor] contained_plots
    DataFrameAnalyzer source_analyzer
    IPlotTemplateInteractor template_interactor
    ..Job Description..
    * Manager to create, update, reorder, hide, delete plots.
    * Provides a data model for a DataFrameAnalyzer.
}
DataFramePlotManager "0..*" o--> PlotDescriptor
DataFramePlotManager o..> DataFrame
DataFramePlotManager o--> DataFrameAnalyzer

class BasePlotFactory {
    ArrayPlotData plot_data
    BaseXYPlotStyle plot_style
    PlotContextMenuManager context_menu_manager
    ..Job Description..
    * Builds a chaco plot with generate_plot()
    * Manipulates titles and ticks/labels for a plot.
}
BasePlotFactory o--> BaseXYPlotStyle
BasePlotFactory o--> PlotContextMenuManager

class StdXYPlotFactory {
    OverlayPlotContainer plot
    {BaseXYPlot} renderers
    ..Job Description..
    * Creates a dict of properties for a 2D plot
    with one or more renderers and a legend.
    * Initializes plot data from arrays.
    * Adds tools (legend/context menu/zoom/pan) to a plot.
    * Builds and adds/appends/removes/updates renderers
}
BasePlotContainer <|-- OverlayPlotContainer
BasePlotFactory <|-- StdXYPlotFactory
StdXYPlotFactory o--> OverlayPlotContainer
OverlayPlotContainer : * Chaco Plot container that stretches all its components

class BaseXYPlotStyle {
    RendererStyleManager renderer_style_manager
    TitleStyle title_style
    PlotContainerStyle container_style
    AxisStyle x_axis_style
    AxisStyle y_axis_style
    AxisStyle second_y_axis_style
    ..Job Description..
    * Used to control and view styling for entire chaco plots.
    * Provides the views for manipulating the plot style.
}
BaseXYPlotStyle o--> RendererStyleManager
BaseXYPlotStyle o--> AxisStyle
BaseXYPlotStyle o--> TitleStyle
BaseXYPlotStyle <|-- BaseColorXYPlotStyle
BaseColorXYPlotStyle <|-- BarPlotStyle

TitleStyle : * Styling tool for a plot title.
AxisStyle : * Styling tool for an axis title.

class RendererStyleManager {
    [BaseRendererStyle] renderer_styles
    ..Job Description..
    * Provides a scrollable view of the renderer style list.
}
RendererStyleManager "0..*" o--> BaseRendererStyle

class BaseRendererStyle {
    Str renderer_name
    ..Job Description..
    * Provides view for customizing individual renderers.
    * Controls marker size, line color, bar width, etc.
}
BaseRendererStyle <|-- BaseXYRendererStyle
BaseXYRendererStyle <|-- ScatterRendererStyle
BaseXYRendererStyle <|-- LineRendererStyle
BaseXYRendererStyle <|-- BarRendererStyle
BaseXYRendererStyle <|-- HeatmapRendererStyle


class PlotDescriptor {
    BasePlotContainer plot
    BasePlotConfigurator plot_config
    BasePlotFactory plot_factory
    ..Job Description..
    * Exposes properties from the plot_config for a TableEditor.
    * Allows user to set frozen/visible status of a plot.
    * Controls events that signify users intent to edit styles.
}
PlotDescriptor o--> BasePlotContainer
PlotDescriptor o--> BasePlotConfigurator
PlotDescriptor o--> BasePlotFactory


class BasePlotConfigurator {
    DataFrame data_source
    DataFrame transformed_data
    BaseXYPlotStyle plot_style
    ..Job Description..
    * Contains and provides all the data required to serialize a plot.
    * Provides the views used to specify plot options and data.
    * Updates the styles when data or options change.
    * Provides default plot styles.
}
BasePlotConfigurator o..> DataFrame
BasePlotConfigurator o--> BaseXYPlotStyle

class BaseSingleXYPlotConfigurator {
    BaseXYPlotStyle plot_style
}
BaseSingleXYPlotConfigurator o--> BaseXYPlotStyle

class BarPlotConfigurator {
    BarPlotStyle plot_style
    DataFrame transformed_data
}
BarPlotConfigurator o..> DataFrame
BarPlotConfigurator o--> BarPlotStyle

class ScatterPlotConfigurator
BasePlotConfigurator <|-- BaseSinglePlotConfigurator
'BasePlotConfigurator <|-- BaseMultiPlotConfigurator
'BaseSingleXYPlotConfigurator <|-- MultiLinePlotConfigurator
'BaseMultiPlotConfigurator <|-- MultiLinePlotConfigurator
BaseSinglePlotConfigurator <|-- BaseSingleXYPlotConfigurator
BaseSingleXYPlotConfigurator <|-- BarPlotConfigurator
BaseSingleXYPlotConfigurator <|-- ScatterPlotConfigurator

@enduml