version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test: # name of your job
    executor: win/default # executor type
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: 
        name: list content
        command: dir
      - run: 
        name : setup edm
        command: |
          INSTALL_EDM_VERSION=3.0.1
          .\install-edm-windows.cmd

workflows:
  main:
    jobs:
      - build-and-test
