version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test: # name of your job
    executor: win/default # executor type
    steps:
      - checkout
      - run: 
          name: list content
          command: dir
      - run: 
          name : setup edm
          command: .\install-edm-windows.cmd
      - run: 
          name: list content
          command: dir
      - run: 
          name: Check edm install
          command: edm --version
      - run:
          name: create dev env
          command: python etstools.py install
      - run:
          name: Run test suite
          command: python etstools.py test

workflows:
  main:
    jobs:
      - build-and-test
