version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test: # name of your job
    executor: win/default # executor type
    steps:
      - checkout
      - run: 
          name : setup edm
          command: .\install-edm-windows.cmd
      - run:
          name: create dev env
          command: |
            pip install click
            python etstool.py install --edm-dir="C:\Users\circleci\AppData\Local\Programs\Enthought\edm\embedded\"
      - run:
          name: Run test suite
          command: python etstool.py test  --edm-dir="C:\Users\circleci\AppData\Local\Programs\Enthought\edm\embedded\"
      - run:
          name: Run flake8
          command: python etstool.py flake8  --edm-dir="C:\Users\circleci\AppData\Local\Programs\Enthought\edm\embedded\"

workflows:
  main:
    jobs:
      - build-and-test
